### ISSUE TITLE
Install Kubernetes Tools fails at multiple points - eksworkshop-admin instance profile

### ISSUE THREAD

**Issue by damo78** [aws-samples/terraform-eks-code#15]
When following this guide: https://catalog.us-east-1.prod.workshops.aws/workshops/afee4679-89af-408b-8108-44f5b1065cc7/en-US/020-prerequisites/k8stools

I've raised an issue for a typo on line 184, but `source setup` doesn't work when called, which is one part of the issue.  But using ./setup at least starts the setup

The output consistently gets stuck at this point below

```
Install OS tools
Update OS tools
Update pip
Uninstall AWS CLI v1
Install AWS CLI v2
Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag.
AWS_REGION is eu-west-1
export ACCOUNT_ID=318781710241
export AWS_REGION=eu-west-1
export AZS=(eu-west-1a eu-west-1b eu-west-1c)
export TF_VAR_region=eu-west-1
eu-west-1
Check Cloud9 AWS Managed temporary credentials are disabled - in AWS Settings
Setup Terraform cache
Setup kubectl
Install kubectl v1.24.12
install eksctl
eksctl completion
helm
add helm repos
"eks" has been added to your repositories
kubectx
ssh key
ssm cli add on
install tfsec ...
pip3
git-remote-codecommit
CHANGED: partition=1 start=4096 old: size=20967391 end=20971487 new: size=67104735 end=67108831
Filesystem     1M-blocks  Used Available Use% Mounted on
/dev/nvme0n1p1     32756  6994     25763  22% /
Verify ....
jq in path
aws in path
wget in path
kubectl in path
terraform in path
eksctl in path
helm in path
kubectx in path
Enable bash_completion
PASSED: AWS_REGION is eu-west-1
PASSED: TF_VAR_region is eu-west-1
PASSED: ACCOUNT_ID is xxxxxxxxxxxx
Associate eksworkshop-admin

An error occurred (InvalidParameterValue) when calling the ReplaceIamInstanceProfileAssociation operation: Value (eksworkshop-admin) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
ERROR: Encountered error associating instance profile eksworkshop-admin with Cloud9 environment
For final checks - run ./check
```

The eksworkshop-admin role has not been created in IAM and there does not appear to be any instance profile associated with the cloud9 instance.

**Comment by awsandy** [comment]
Are you running this in your own environment - or in an AWS event (via workshop studio) ?

**Comment by awsandy** [comment]
typo fix committed for line 184 in setup

instructions changed to run:  source ./setup

Also removed the workshop section on running in your own account - as this needs more testing / different instructions

So workshop only tested / usable in workshop studio (AWS events) for now.

**Comment by damo78** [comment]
It was in my own environment Andy.  I'll look forward to seeing it again in the future.  

In the meantime I'm going to try and create my own TF and piece together the k8s side from the tfekscode.
