### ISSUE TITLE
kubectl would only use default context from the running env

### ISSUE THREAD

**Issue by zhangluva** [aws-samples/terraform-eks-code#2]
I spent some time figuring out a weird problem. Why my deployment to cluster A would cause target groups in cluster B to be deregistered. 
It turned out I sometimes set Cluster B as the current context from another terminal for other purposes, and the kubectl commands in this example will apply all changes (especially delete CRD) to cluster B (instead of cluster A).
Would be nice to remove this uncertainty from the equation. e.g. make sure to use and only use the cluster that we are working on.
https://github.com/aws-samples/terraform-eks-code/blob/7674a91ab8048ba36e10bfd138d8efaf4dba43db/lb2/null_destoy.tf#L15

**Comment by awsandy** [comment]
Fixed this specific issue by a quick call to kubectx before the kubectl delete
