### ISSUE TITLE
Route table association question

### ISSUE THREAD

**Issue by AnatoliM** [aws-samples/terraform-eks-code#5]
Hello,

Thanks for such a wonderful workshop. Learned a lot from it. Sorry if my question is too trivial, but networking is not my forte.

Folder `/net` defines two groups of three private subnets, marked with `p1`, `p2`, and `p3`, and `i1`, `i2`, and `i3` suffixes. There are four routing tables declared, named `rtb-0102c621469c344cd`, `rtb-0329e787bbafcb2c4`, `rtb-041267f0474c24068`, and `rtb-0939e7f3ae6e7b829`. 

Then there is a bunch of `aws_route_table_association__rtbassoci-` files linking them. What I see (in master branch) is three declarations associating `rtb-0329e787bbafcb2c4` with `i1`, `i2`, and `i3` on one end and always `p3` on the other. On the other hand, `rtb-0102c621469c344cd` and `rtb-041267f0474c24068`are associated with `p2` and `p1` respectively, but no `i` anything at all. Quite likely I am grossly misunderstanding the design, but my expectation was that one `iN` is to be associated with one `pN`. Could you please clarify?

And `rtb-0939e7f3ae6e7b829` has no associations whatsoever. Does this mean that this routing table is not being used?
 
Thank you very much,
-Anatoli

**Comment by awsandy** [comment]
Hi,

I've tidied that all up now so it should make more sense.

Thanks for spotting it !

As is happens all these route tables end up with the same entries - so we could collapse / simplify it further
