### ISSUE TITLE
IAM policy question

### ISSUE THREAD

**Issue by AnatoliM** [aws-samples/terraform-eks-code#6]
Hello,

This doc (https://aws.amazon.com/blogs/mt/applying-managed-instance-policy-best-practices/) suggests that `AmazonEC2RoleforSSM` policy should be deprecated in favor of more granular `AmazonSSMManagedInstanceCore`.

Your declarations add both of them. Is deprecated one still necessary for some reason?

Thanks,
-Anatoli

**Comment by awsandy** [comment]
It should just work with AmazonSSMManagedInstanceCore, testing pending here .....

**Comment by awsandy** [comment]
just using core now
